apiVersion: extensions/v1beta1
kind: Pod
metadata:
    name: demo-service-deployment
    labels:
        app: demo-service
spec:
    containers:
    - name: demo-service-springboot
        image: chaitanya2409/springbootdockertest
        ports:
        - containerPort: 8090